## Indexes
## Datatype
## Access elements
## Operations

In [3]:
import pandas as pd

### Customized Indexes

In [4]:
s1 = pd.Series([11, 22, 33, 44, 55], index = ['a', 'b', 'c', 'd', 'e']) # Agregamos un Ã­ndice personalizado
s1

a    11
b    22
c    33
d    44
e    55
dtype: int64

### Datatype of serie

In [5]:
s1 = pd.Series([11, 22, 33, 44, 55], dtype = 'float')
s1

0    11.0
1    22.0
2    33.0
3    44.0
4    55.0
dtype: float64

### Accesing data from the serie

In [6]:
s1 = pd.Series([11, 22, 33, 44, 55])

In [7]:
s1[0] # Accedemos al valor por su indice

np.int64(11)

In [8]:
s1[1]

np.int64(22)

In [9]:
s1[0:2]  # primer indice, desde donde; segundo indice, hasta cual menos 1

0    11
1    22
dtype: int64

In [10]:
s1[1:3]

1    22
2    33
dtype: int64

### Operations on pandas series

In [11]:
s1 = pd.Series([1, 2, 3, 4])
s2 = pd.Series([10, 20, 30, 40])

In [12]:
# Suma
s1 + s2

0    11
1    22
2    33
3    44
dtype: int64

In [18]:
# Resta
s2 - s1

0     9
1    18
2    27
3    36
dtype: int64

In [13]:
# MultiplicaciÃ³n
s1 * s2

0     10
1     40
2     90
3    160
dtype: int64

In [14]:
# DivisiÃ³n
s1 / s2

0    0.1
1    0.1
2    0.1
3    0.1
dtype: float64

In [16]:
# Exponente
s1**2

0     1
1     4
2     9
3    16
dtype: int64

In [21]:
# Cuando las series no contiene la misma cantidad de elementos (Not a Number)
s1 = pd.Series([1, 2, 3, 4])
s2 = pd.Series([10, 20, 30])

s1 + s2

0    11.0
1    22.0
2    33.0
3     NaN
dtype: float64

### Ejemplo

In [23]:
serie1 = pd.Series([1, 2, 3, 4])

serie2 = pd.Series([10, 20, 30, 40])

In [24]:
serie1 // serie2

0    0
1    0
2    0
3    0
dtype: int64

In [25]:
serie1 / serie2

0    0.1
1    0.1
2    0.1
3    0.1
dtype: float64